stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker --version  # Check Docker version to ensure Docker is available
    - echo "Done"
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying..."
    - docker-compose up -d
    - echo "Waiting for backend to start..."
    - sleep 30  # Wait for the backend to start up
    - curl -f http://sekretariat-api/contracts || exit 1  # Exit with error if health check fails
    - echo "Deployment complete"
  only:
    - main
