stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: $DOCKER_REGISTRY/pb-pbm-mmu/sekretariat
  DOCKER_TAG: $CI_COMMIT_REF_SLUG
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - echo "Docker images after build:"
    - docker images
  only:
    - main
    - tags

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Logging in to Docker registry..."
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - echo "Pushing Docker image..."
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - echo "Docker images before push:"
    - docker images
  only:
    - main
    - tags
