stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: $DOCKER_REGISTRY/your-namespace/your-project
  DOCKER_TAG: $CI_COMMIT_REF_SLUG

# Build Docker image
build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  only:
    - main
    - tags

# Push Docker image to GitLab Container Registry
deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main
    - tags
