version: '3'

services:
  app:
    image: sekretariat:latest
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Admin#1234
      - DB_NAME=sys
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Admin#1234
      MYSQL_DATABASE: sys
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306
